

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.PasswordAuthentication;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Transport;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Arnie D
 */
public class Send_Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Send_Ticket
     */
    public Send_Ticket() {
        initComponents();
        Connect();
        Requester();
        getEmail();
        getDepartment();
         getPassword();
         LoadPlaceName();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
   int xMouse;
    int yMouse;
    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tickets_jdc", "root", "admin");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Ticketing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void Requester(){
      String name = Ticketing.user.getText();
      try{
          pst = con.prepareStatement("Select * from users where user_name=? ");
          pst.setString(1, name);
          rs=pst.executeQuery();
          if(rs.next()){
              String first_name = rs.getString("first_name");
              String last_name = rs.getString("last_name");
              requester.setText(first_name + " " + last_name);
          }
        } catch (SQLException ex) {
            Logger.getLogger(User_Ticket.class.getName()).log(Level.SEVERE, null, ex);

        }
      
    }
    public void getEmail(){
        String mail = Ticketing.user.getText();
      try{
          pst = con.prepareStatement("Select * from users where user_name=? ");
          pst.setString(1, mail);
          rs=pst.executeQuery();
          if(rs.next()){
              String mails = rs.getString("email");
              email.setText(mails);
              
          }
        } catch (SQLException ex) {
            Logger.getLogger(User_Ticket.class.getName()).log(Level.SEVERE, null, ex);

        }
    }
        public void getDepartment(){
        String dept = Ticketing.user.getText();
      try{
          pst = con.prepareStatement("Select * from users where user_name=? ");
          pst.setString(1, dept);
          rs=pst.executeQuery();
          if(rs.next()){
              String depta = rs.getString("department");
              department.setSelectedItem(depta);
              
          }
        } catch (SQLException ex) {
            Logger.getLogger(User_Ticket.class.getName()).log(Level.SEVERE, null, ex);

        }
    }
        public void getPassword(){
           String pass = Ticketing.user.getText();
      try{
          pst = con.prepareStatement("Select * from users where user_name=? ");
          pst.setString(1, pass);
          rs=pst.executeQuery();
          if(rs.next()){
              String pas = rs.getString("App_password");
              label_pas.setText(pas);
              
          }
        } catch (SQLException ex) {
            Logger.getLogger(User_Ticket.class.getName()).log(Level.SEVERE, null, ex);

        } 
        }
         public void LoadPlaceName(){
        
        try {
            String sql = "SELECT * FROM users where level_of_access = 'Admin' ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            while (rs.next()){
                String firstname = rs.getString("first_name");
                String lastname = rs.getString("last_name");
                access.addItem(firstname + " " + lastname);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Send_Ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        requester = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        subject = new javax.swing.JTextField();
        label_pas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        access = new javax.swing.JComboBox<>();
        cancel = new javax.swing.JButton();
        send = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(228, 57, 39));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(228, 57, 39));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Requester:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        requester.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        requester.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        requester.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        requester.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        requester.setEnabled(false);
        jPanel3.add(requester, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 330, 37));

        jLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("Email:");
        jPanel3.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        email.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        email.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        email.setEnabled(false);
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 330, 37));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Message:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        subject.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        subject.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        subject.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 330, 37));

        label_pas.setBackground(new java.awt.Color(228, 57, 39));
        label_pas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_pas.setForeground(new java.awt.Color(228, 57, 39));
        jPanel3.add(label_pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 180, 30));

        msg.setColumns(20);
        msg.setLineWrap(true);
        msg.setRows(5);
        msg.setMaximumSize(new java.awt.Dimension(232, 84));
        jScrollPane1.setViewportView(msg);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 700, 180));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Assignee:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT Department", "HR Department", "Admin Department", "Purchasing Department", "Treasury Department" }));
        department.setEnabled(false);
        jPanel3.add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 330, 37));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Department:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        access.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessActionPerformed(evt);
            }
        });
        jPanel3.add(access, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 330, 37));

        cancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel3.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 130, -1));

        send.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        send.setText("Send");
        send.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel3.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 130, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Subject:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 540));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 792, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void accessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accessActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
        User_Ticket user = new User_Ticket();
        user.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        String sub = subject.getText();
        String msgs = msg.getText();

        if(sub.equals("")||msgs.equals("")){
             JOptionPane.showMessageDialog(null, "Please input all the necessary information", "Hey!", JOptionPane.ERROR_MESSAGE);
             subject.requestFocus();
        }
        else{

        String assgn = access.getSelectedItem().toString();
        String to = null;
        if (assgn.equals("Arnie del Rosario")){
            to = "arniemonidelrosario@gmail.com";
        }
        else{
             to = "arniemonica.delrosario@cvsu.edu.ph";
        }
        
        String request = requester.getText();
        String from = email.getText();
        String pass = label_pas.getText();
         
        String dept = department.getSelectedItem().toString();
        String stats = "Open";
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date date = new Date();  
        String dt = formatter.format(date);
        
        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");    
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");

        Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(from, pass);
            }
        });

        try {
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            message.setSubject(sub);
            message.setText(msg.getText());
            Transport.send(message);
            
           
            
           pst = con.prepareStatement("Insert into tickets( Requester,Email,Subject,Message,department,Assignee,Assignee_Email,Status,Sent,Status_Change) values (?,?,?,?,?,?,?,?,?,?)");
           pst.setString(1,request);
           pst.setString(2,from);
           pst.setString(3,sub);
           pst.setString(4,msgs);
           pst.setString(5,dept);
           pst.setString(6,assgn);
           pst.setString(7,to);
           pst.setString(8,stats);
           pst.setString(9,dt);
           pst.setString(10,"");
           int saved =pst.executeUpdate();
             
            JOptionPane.showMessageDialog(null, "Your message sent successfully");
            User_Ticket user = new User_Ticket();
            user.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            System.out.println(ex);
        }
        }

    }//GEN-LAST:event_sendActionPerformed

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseReleased

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       
       this.setLocation(x-xMouse,y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Send_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Send_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Send_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Send_Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Send_Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> access;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> department;
    public static javax.swing.JTextField email;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_pas;
    private javax.swing.JTextArea msg;
    private javax.swing.JTextField requester;
    private javax.swing.JButton send;
    private javax.swing.JTextField subject;
    // End of variables declaration//GEN-END:variables
}
